name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        variant: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake gcc make
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }}
          make
          sudo make install