name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        variant: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and test
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake gcc make doxygen lcov gcovr
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.variant }} -DBUILD_TESTS=ON
          make -j4
          ctest
          sudo make install
          cd ..
          gcovr --filter='include/' --print-summary --sort-percentage